/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "frwhbijklphmujntvetl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyd2hiaWprbHBobXVqbnR2ZXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MzM0MzQsImV4cCI6MjA3NzIwOTQzNH0.lNtQVBPkG3CGxe-bOERSij-x0ZAzkb5k2pI6frf2Ezs"